### PR TITLE
Fix broken tests on Mac OSX

### LINKED ISSUE #873: Bug: Tests on Mac OSX are not running anymore
**Bug report**
After changes to the platform inference, multiple tests stopped working on Mac OSX.

**To reproduce**

**System info**
- macOS Catalina
-GNU bash, Version 5.0.17(1)-release (x86_64-apple-darwin18.7.0)
- SDKMAN master+647

There seem to be multiple problems which lead to the tests failing. 

1. `UnixUtils.groovy` infers the wrong platform

UnixUtils.groovy expects `System.getProperty("os.name")` to resolve to `Darwin`, while it actually resolves to `Mac OS X`.

```
jshell> System.getProperty("os.name")
$1 ==> "Mac OS X"
```

Interestingly, `uname -s` returns `Darwin` on my machine 😕. 

2. `UnameStub` by default uses platform/kernel `Linux` and machine `X86_64`. This causes problems on Mac OSX, because SDKMAN! then chooses a non-compatible version of `sed`.

This could probably be fixed by replacing the platform-dependent code with shell builtins (this would also slightly improve performance, as less processes need to be forked).

### PR DESCRIPTION
**Pull request by helpermethod**
Fixes #873.

### CODE REVIEW

**Comment by marc0der** [comment]
Awesome work!

I merged a fix to get the build green. Would you mind rebasing on master to get this green?

File: src/test/groovy/sdkman/support/SdkmanEnvSpecification.groovy [hunk 1]
```diff
@@ -11,7 +10,6 @@ abstract class SdkmanEnvSpecification extends BashEnvSpecification {
 	SdkmanBashEnvBuilder sdkmanBashEnvBuilder
 
 	CurlStub curlStub
-	UnameStub unameStub
```
Comment (marc0der) [inline src/test/groovy/sdkman/support/SdkmanEnvSpecification.groovy:14]: It feels like this should be here because it is a base class for all the specs. wdyt?

File: src/test/groovy/sdkman/specs/PlatformSpec.groovy [hunk 2]
```diff
@@ -1,9 +1,13 @@
 package sdkman.specs
 
+import sdkman.stubs.UnameStub
 import sdkman.support.SdkmanEnvSpecification
 
 class PlatformSpec extends SdkmanEnvSpecification {
+	UnameStub unameStub
```
Comment (marc0der) [inline src/test/groovy/sdkman/specs/PlatformSpec.groovy:7]: Is it possible to rely on the base class here if we put it back into the `SdkmanEnvSpecification`? The purpose of that class is, so we don't need to create any fixture like this manually.

Comment (helpermethod) [reply src/test/groovy/sdkman/specs/PlatformSpec.groovy:7]: The problem is that if you call `UnameStub.prepareIn` in the base class it will always create an empty `uname` file, which will break a lot of tests on non-Linux systems. Calling `prepareIn` only makes sense if you also call `forKernel` and `forMachine` *and* `build`.

Comment (helpermethod) [reply src/test/groovy/sdkman/specs/PlatformSpec.groovy:7]: Or maybe I misunderstood you 😄 .

Comment (helpermethod) [reply src/test/groovy/sdkman/specs/PlatformSpec.groovy]: The fixture is now created in the base class again.

**Comment by helpermethod** [comment]
Okay, one last try 😄 . Now the `UnameStub` is *always* used but platform / arch / machine are resolved from Java system properties.

**Review by marc0der — APPROVED** [review]
Great stuff!
